name: deploy-static-files-to-s3

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 's3 Deployment' }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.FRONTEND_DEPLOYMENT_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.FRONTEND_DEPLOYMENT_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Build Nuxt App Static Files
        working-directory: ./frontend
        run: npm install &&  npm run build && npm run generate
      - name: Deploy App build to S3 bucket
        working-directory: ./frontend
        run: aws s3 sync ./build/ s3://apphasia --delete
